language: android
android:
  components:
    - build-tools-27.0.3
    - android-27
    - extra 
notifications:
    slack: osmarsfavoriteteam:DonXX1YhIre5zNHPwPq083Mv
before_install:
  - sdkmanager --update && yes | sdkmanager --licenses
