language: android
android:
  components:
    - build-tools-27.1.0
    - android-27
    - extra 
notifications:
    slack: osmarsfavoriteteam:DonXX1YhIre5zNHPwPq083Mv
before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-26"
