language: android
android:
  components:
    - build-tools-27.0.3
    - android-27
    - extra
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-17 
notifications:
    slack: osmarsfavoriteteam:DonXX1YhIre5zNHPwPq083Mv
before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-26"
